#helm repo add eks https://aws.github.io/eks-charts
#helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=prod-expense -f ingress.yaml



serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::008089408493:role/prod-expense-aws-load-balancer-controller-sa



#eks.amazonaws.com/role-arn: arn:aws:iam::008089408493:role/prod-expense{{ .Values.appName }}-eks-sa

